### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by gmoring** [DennisWG/QuickBind#1]
Hi DennisWG,

I'm a bit stumped as to how to use this addon. I attempted to call it with "/qb", which seemed to work- I was then able to easily assign a key binding by hovering over an actionBar item. But then I was unable to turn the binding mode off. I tried Escape first, then tried to run "/qb" again, but I couldn't interface with the chat box due to the binding mode still being on. 

Sorry if I'm missing something obvious, but I would appreciate your advice on how to use your addon when you get a chance. Thanks for the help, sir, and nice job on the addon!

**Comment by DennisWG** [comment]
The binding mode should turn off when you type `/qb` again while not hovering over any buttons. Can you confirm that you did not hover your mouse over any button?

**Comment by ehatle** [comment]
I was not able to type /qb again as the addon bound the ENTER key to the action bar
